"""Centralized exception hierarchy for the entire application."""
from .base import (
    ApplicationException,
    AuthenticationException,
    AuthorizationException,
    BusinessException,
    ConfigurationException,
    ConflictException,
    DatabaseException,
    ExportException,
    ExternalServiceException,
    InvalidInputException,
    LogLevel,
    NotFoundException,
    PipelineException,
    RateLimitException,
    TimeoutException,
    TranscriptNotFoundException,
    ValidationException,
    VideoNotFoundException,
    YouTubeAPIException,
    YouTubeQuotaException,
)
from .youtube_errors import InvalidVideoIDError, UnsupportedURLError, YouTubeURLError

__all__ = [
    "ApplicationException",
    "AuthenticationException",
    "AuthorizationException",
    "BusinessException",
    "ConfigurationException",
    "ConflictException",
    "DatabaseException",
    "ExportException",
    "ExternalServiceException",
    "InvalidInputException",
    "LogLevel",
    "NotFoundException",
    "PipelineException",
    "RateLimitException",
    "TimeoutException",
    "TranscriptNotFoundException",
    "ValidationException",
    "VideoNotFoundException",
    "YouTubeAPIException",
    "YouTubeQuotaException",
    "InvalidVideoIDError",
    "UnsupportedURLError",
    "YouTubeURLError",
]

